import { VirtualGift, StreamRoom, User, ShortReel, NotificationItem } from './types';

export const CURRENT_USER: User = {
  id: 'usr_me',
  name: 'Alvin',
  handle: 'alvin_official',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  country: 'India',
  countryFlag: '🇮🇳',
  level: 12,
  vipLevel: 3,
  svip: true,
  agency: 'VibeMedia Agency',
  isVerified: true,
  bio: '✨ Live Streamer & Singer | Daily 8 PM IST 🎤 | SVIP Member',
  followers: 10420,
  following: 1120,
  friends: 1050,
  visitors: 2430,
  coins: 8500,
  diamonds: 14200,
};

export const VIRTUAL_GIFTS: VirtualGift[] = [
  { id: 'g_rose', name: 'Rose', icon: '🌹', priceCoins: 10, category: 'popular', animationType: 'float' },
  { id: 'g_heart', name: 'Love Heart', icon: '💖', priceCoins: 50, category: 'popular', animationType: 'float' },
  { id: 'g_boba', name: 'Boba Tea', icon: '🧋', priceCoins: 100, category: 'popular', animationType: 'float' },
  { id: 'g_crown', name: 'Royal Crown', icon: '👑', priceCoins: 500, category: 'luxury', animationType: 'explosion' },
  { id: 'g_ring', name: 'Diamond Ring', icon: '💍', priceCoins: 1200, category: 'luxury', animationType: 'explosion' },
  { id: 'g_car', name: 'Sports Car', icon: '🏎️', priceCoins: 5000, category: 'luxury', animationType: 'sportsCar' },
  { id: 'g_castle', name: 'Magic Castle', icon: '🏰', priceCoins: 10000, category: 'vip', animationType: 'castle' },
  { id: 'g_dragon', name: 'Golden Dragon', icon: '🐉', priceCoins: 25000, category: 'vip', animationType: 'dragon' },
  { id: 'g_rocket', name: 'Space Rocket', icon: '🚀', priceCoins: 50000, category: 'effects', animationType: 'dragon' },
];

export const MOCK_STREAMS: StreamRoom[] = [
  {
    id: 'room_1',
    title: '🎵 Acoustic Vibes & Chat | Stage Seats Open!',
    type: 'video',
    mode: 'multi',
    category: 'Music',
    country: 'India',
    countryFlag: '🇮🇳',
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-sign-1232-large.mp4',
    viewerCount: 1420,
    likeCount: 18900,
    tags: ['Acoustic', 'Music', 'Interactive'],
    isHot: true,
    isRecommended: true,
    durationSeconds: 3600,
    pinnedMessage: 'Welcome to the Live Stage! Tap any empty "+ Slot" to join the stage with video or audio! 🎤✨',
    host: {
      id: 'usr_host_1',
      name: 'Aria Sharma',
      handle: 'aria_music',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
      country: 'India',
      countryFlag: '🇮🇳',
      level: 42,
      vipLevel: 4,
      svip: true,
      isVerified: true,
      bio: 'Singer & Songwriter 🎧',
      followers: 48900,
      following: 180,
      friends: 320,
      visitors: 8900,
      coins: 24500,
      diamonds: 120000,
    },
    guests: [],
  },
  {
    id: 'room_solo_1',
    title: '🔥 Solo Broadcast: Guitar Jamming & Q&A 🎸',
    type: 'video',
    mode: 'multi',
    category: 'Music',
    country: 'India',
    countryFlag: '🇮🇳',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-sign-1232-large.mp4',
    viewerCount: 3420,
    likeCount: 48900,
    tags: ['Solo', 'Guitar', 'Music'],
    isHot: true,
    isRecommended: true,
    durationSeconds: 1200,
    pinnedMessage: 'Welcome to the Live Stream! Tap a stage slot to join me on stage! ✨',
    host: {
      id: 'usr_maya',
      name: 'Maya Lin',
      handle: 'maya_sing',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
      country: 'India',
      countryFlag: '🇮🇳',
      level: 45,
      vipLevel: 5,
      svip: true,
      isVerified: true,
      bio: 'Singer & Songwriter 🎧',
      followers: 89000,
      following: 240,
      friends: 420,
      visitors: 12000,
      coins: 45000,
      diamonds: 189000,
    },
    guests: []
  },
  {
    id: 'room_solo_2',
    title: '✨ Daily Vlog Live: Chatting, Coffee & Vibes ☕',
    type: 'video',
    mode: 'solo',
    category: 'Music',
    country: 'USA',
    countryFlag: '🇺🇸',
    coverImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-talking-on-video-call-41123-large.mp4',
    viewerCount: 2180,
    likeCount: 27500,
    tags: ['Solo', 'Vlog', 'Chill'],
    isHot: true,
    isRecommended: true,
    durationSeconds: 2400,
    pinnedMessage: 'Thanks for tuning in! Sending love to everyone in chat 💕',
    host: {
      id: 'usr_chloe',
      name: 'Chloe Bennett',
      handle: 'chloe_love',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
      country: 'USA',
      countryFlag: '🇺🇸',
      level: 39,
      vipLevel: 4,
      svip: true,
      isVerified: true,
      bio: 'Spread Love & Positivity ❤️',
      followers: 67000,
      following: 310,
      friends: 980,
      visitors: 15000,
      coins: 34000,
      diamonds: 145000,
    },
    guests: []
  },
  {
    id: 'room_1',
    title: '🎵 Acoustic Vibes & Chat | Taking Song Requests!',
    type: 'video',
    mode: 'multi',
    category: 'Music',
    country: 'India',
    countryFlag: '🇮🇳',
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800',
    viewerCount: 1240,
    likeCount: 18500,
    tags: ['Music', 'Singing', 'Acoustic'],
    isHot: true,
    isRecommended: true,
    durationSeconds: 3420,
    pinnedMessage: '👉 Type !song in chat to request your favorite track!',
    host: {
      id: 'usr_maya',
      name: 'Maya Lin',
      handle: 'maya_sing',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
      country: 'India',
      countryFlag: '🇮🇳',
      level: 45,
      vipLevel: 5,
      svip: true,
      isVerified: true,
      bio: 'Singer & Songwriter 🎧',
      followers: 89000,
      following: 240,
      friends: 420,
      visitors: 12000,
      coins: 45000,
      diamonds: 189000,
    },
    guests: []
  },
  {
    id: 'room_2',
    title: '💬 Midnight Voice Lounge - Chill Music & Deep Talk',
    type: 'audio',
    category: 'Audio Room',
    country: 'Philippines',
    countryFlag: '🇵🇭',
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800',
    viewerCount: 890,
    likeCount: 9400,
    tags: ['Podcast', 'Chill', 'Voice'],
    isHot: true,
    isRecommended: true,
    durationSeconds: 1800,
    pinnedMessage: 'Welcome everyone! Tap any empty seat to request mic 🎤',
    host: {
      id: 'usr_sam',
      name: 'Samantha Vance',
      handle: 'sam_voice',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400',
      country: 'Philippines',
      countryFlag: '🇵🇭',
      level: 32,
      vipLevel: 3,
      svip: false,
      isVerified: true,
      bio: 'Late night host 🎙️',
      followers: 45000,
      following: 500,
      friends: 800,
      visitors: 6700,
      coins: 12000,
      diamonds: 64000,
    },
    guests: []
  },
  {
    id: 'room_3',
    title: '🎮 Ranked Valorant Tournament & Viewer Games!',
    type: 'gaming',
    category: 'Gaming',
    country: 'Turkey',
    countryFlag: '🇹🇷',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800',
    viewerCount: 2340,
    likeCount: 34100,
    tags: ['Gaming', 'Esports', 'Valorant'],
    isHot: true,
    isRecommended: false,
    durationSeconds: 5400,
    pinnedMessage: 'Join discord for custom lobby codes! 🏆',
    host: {
      id: 'usr_alex',
      name: 'Alex Gamer',
      handle: 'alex_fps',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
      country: 'Turkey',
      countryFlag: '🇹🇷',
      level: 52,
      vipLevel: 6,
      svip: true,
      isVerified: true,
      bio: 'Pro Gamer 🕹️',
      followers: 125000,
      following: 80,
      friends: 1200,
      visitors: 45000,
      coins: 98000,
      diamonds: 340000,
    },
    guests: []
  },
  {
    id: 'room_4',
    title: '❤️ Love & CP Matching Room - Find Your Bestie!',
    type: 'cp',
    category: 'CP Matching',
    country: 'USA',
    countryFlag: '🇺🇸',
    coverImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=800',
    viewerCount: 1560,
    likeCount: 22000,
    tags: ['CP', 'Dating', 'Fun'],
    isHot: false,
    isRecommended: true,
    durationSeconds: 2700,
    pinnedMessage: 'Send a heart gift to join the CP match lineup! 💕',
    host: {
      id: 'usr_chloe',
      name: 'Chloe Bennett',
      handle: 'chloe_love',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
      country: 'USA',
      countryFlag: '🇺🇸',
      level: 39,
      vipLevel: 4,
      svip: true,
      isVerified: true,
      bio: 'Spread Love & Positivity ❤️',
      followers: 67000,
      following: 310,
      friends: 980,
      visitors: 15000,
      coins: 34000,
      diamonds: 145000,
    },
    guests: []
  }
];

export const MOCK_REELS: ShortReel[] = [
  {
    id: 'reel_1',
    user: MOCK_STREAMS[0].host,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-sign-lighting-1232-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=400',
    caption: 'Late night neon vibe & acoustic rehearsal ✨ Live stream daily at 8PM IST!',
    likes: 14200,
    comments: 320,
    shares: 110,
    musicTitle: 'Original Sound - Maya Lin Acoustic',
    isLiked: true,
  },
  {
    id: 'reel_2',
    user: MOCK_STREAMS[2].host,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-a-smartphone-playing-a-game-41427-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=400',
    caption: 'Insane 1v4 clutch in Valorant tournament!! 🔥 Join my room for viewer games!',
    likes: 28900,
    comments: 890,
    shares: 450,
    musicTitle: 'Cyberpunk Synthwave Beats',
    isLiked: false,
  },
  {
    id: 'reel_3',
    user: MOCK_STREAMS[1].host,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-singing-singer-holding-a-microphone-40333-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=400',
    caption: 'Live studio vocal cover session 🎤 Voice audio room active right now!',
    likes: 9800,
    comments: 210,
    shares: 95,
    musicTitle: 'Acoustic Vocal Medley - Sam',
    isLiked: false,
  },
  {
    id: 'reel_4',
    user: MOCK_STREAMS[3].host,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-dancing-in-a-neon-room-41584-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=400',
    caption: 'Choreography dance rehearsal 💃 Come join our CP matching party room!',
    likes: 34100,
    comments: 1200,
    shares: 870,
    musicTitle: 'Top 40 Dance Anthem Remix',
    isLiked: true,
  },
  {
    id: 'reel_5',
    user: {
      id: 'usr_leo',
      name: 'Leo Beats',
      handle: 'leo_beats',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
      country: 'USA',
      countryFlag: '🇺🇸',
      level: 28,
      vipLevel: 2,
      svip: false,
      isVerified: false,
      bio: 'Guitarist',
      followers: 12000,
      following: 110,
      friends: 95,
      visitors: 1400,
      coins: 2000,
      diamonds: 8900,
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-a-young-man-playing-the-guitar-and-singing-41315-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&q=80&w=400',
    caption: 'Late night solo guitar session 🎸 Drop your favorite track in comments!',
    likes: 18500,
    comments: 430,
    shares: 210,
    musicTitle: 'Chill Acoustic Solos',
    isLiked: false,
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    type: 'gift',
    user: MOCK_STREAMS[0].host,
    text: 'sent you a Royal Crown 👑 gift!',
    timestamp: '2m ago',
    isRead: false,
  },
  {
    id: 'notif_2',
    type: 'follow',
    user: MOCK_STREAMS[1].host,
    text: 'started following you.',
    timestamp: '15m ago',
    isRead: false,
  },
  {
    id: 'notif_3',
    type: 'like',
    user: MOCK_STREAMS[2].host,
    text: 'liked your live stream highlight reel.',
    timestamp: '1h ago',
    isRead: true,
  }
];
